Repository k1LoW/runn, pull requests merged in 2022-11, with the labels that each got.

#251 Fix rprof --sort
  cmd/rprof.go
Labels: bug

#253 [BREAKING] Support `--random` option for CLI and `RunRandom` option for test helper
  book.go
  cmd/list.go
  cmd/loadt.go
  cmd/root.go
  cmd/run.go
  operator.go
  operator_test.go
  option.go
  option_test.go
Labels: enhancement, minor

#257 Support Chrome DevTools Protocol (CDP)
  .github/workflows/ci.yml
  Makefile
  README.md
  book.go
  capture/runbook.go
  capturer.go
  cdp.go
  cdp_test.go
  cdpfn.go
  cmdout.go
  debugger.go
  debugger_test.go
  go.mod
  go.sum
  id.go
  integration_test.go
  operator.go
  operator_test.go
  option.go
  option_test.go
  parse.go
  scripts/fndoc.go
  testdata/book/cdp.yml
  testdata/cdp.yml.debugger.golden
  testutil/cdp.go
Labels: enhancement, minor

#264 Fix timing of record step value on Dump runner and Bind runner.
  operator.go
Labels: bug

#269 Fix panic: reflect: Call using zero Value argument
  cdp.go
Labels: bug

#273 [BREAKING] AfterFuncs will run even if the scenario fails
  errors.go
  operator.go
  operator_test.go
  testdata/book/always_failure.yml
  testdata/book/always_success.yml
Labels: minor

#275 [BREAKING] Make AfterFuncs receive runbook run error
  book.go
  operator.go
  operator_test.go
  option.go
Labels: minor

#280 [BREAKING] Rename CaptureFailed to CaptureFailure
  capture/runbook.go
  capturer.go
  cmdout.go
  debugger.go
  exec_test.go
Labels: minor

#279 [BREAKING] Support JSON output of RunN result
  cmd/root.go
  cmd/run.go
  operator.go
  operator_test.go
  result.go
  result_test.go
  testdata/result_out_0.golden
  testdata/result_out_1.golden
  testdata/result_out_2.golden
  testdata/result_out_json_0.golden
  testdata/result_out_json_1.golden
  testdata/result_out_json_2.golden
Labels: minor

#283 Support multipart/form-data via http
  README.md
  capture/runbook_test.go
  http.go
  http_test.go
  http_validator.go
  operator_test.go
  testdata/book/http_multipart.yml
  testdata/dummy.jpeg
  testdata/dummy.png
  testdata/http_multipart.yml.runbook.golden
  testdata/openapi3.yml
  testutil/http.go
Labels: enhancement, minor

#302 Handle expand error
  runbook.go
Labels: bug

#307 Add `localStorage` `sessionStorage` to cdpfn
  README.md
  cdp_test.go
  cdpfn.go
  testutil/http.go
Labels: enhancement, minor

#314 [BREAKING] Change function signature of BeforeFunc args
  book.go
  include.go
  operator.go
  operator_test.go
  option.go
  result.go
Labels: minor

#315 Support SSH
  book.go
  go.mod
  go.sum
  id.go
  integration_test.go
  operator.go
  operator_test.go
  option.go
  option_test.go
  parse.go
  ssh.go
  step.go
  testdata/book/sshd.yml
  testdata/sshd/entrypoint.d/setkeys.sh
  testdata/sshd/entrypoint.d/sudo.sh
  testdata/sshd/id_rsa
  testdata/sshd/id_rsa.pub
  testdata/sshd/ssh_config
  testutil/http.go
Labels: enhancement, minor

#316 [BREAKING] Support capturing SSH command stdout and stderr
  capture/runbook.go
  capturer.go
  cmdout.go
  debugger.go
  ssh.go
Labels: minor

#325 [BREAKING] Add KeepSession Option / Set keepSession to default false
  README.md
  book.go
  integration_test.go
  option.go
  runner_option.go
  ssh.go
  testdata/book/sshd.yml
  testdata/book/sshd_keep_session.yml
Labels: minor

#331 Reset headers as well
  http.go
Labels: bug

#337 Fix handling result
  operator.go
  operator_test.go
  result.go
  result_test.go
  testdata/result_out_0.golden
  testdata/result_out_1.golden
  testdata/result_out_2.golden
  testdata/result_out_json_0.golden
  testdata/result_out_json_1.golden
  testdata/result_out_json_2.golden
Labels: bug

#339 Add path resolution for setUploadFile.path
  cdp.go
Labels: bug
