Repository k1LoW/runn, pull requests merged in 2023-04, with the labels that each got.

#478 Support `force:` section to force all steps to run.
  README.md
  book.go
  include.go
  operator.go
  operator_test.go
  option.go
  parse.go
  runbook.go
  testdata/book/force.yml
Labels: enhancement, minor

#483 Generate `outcome` store values even if runbook is skipped
  operator.go
  operator_test.go
Labels: breaking-change

#482 Add Cloud Spanner support without `xo/dburl`
  README.md
  db.go
  go.mod
  go.sum
Labels: minor

#485 Fix `runn run` output ( Show runbook path / Add `--verbose` option )
  capture/runbook.go
  capturer.go
  cmd/run.go
  cmdout.go
  debugger.go
  flags/flags.go
  operator.go
  operator_test.go
  result.go
  step.go
Labels: enhancement, minor, breaking-change

#487 Fix output JSON of `runn run --format json`
  operator.go
  operator_test.go
  result.go
  result_test.go
  testdata/result_out_json_0.golden
  testdata/result_out_json_1.golden
  testdata/result_out_json_2.golden
Labels: minor, breaking-change

#488 Fix output of `runn run`
  cmdout.go
  operator.go
Labels: breaking-change

#494 If the loop is run a specified number of times and there is an error, the runbook run will result in an error ( for simple loop )
  operator.go
  operator_test.go
  testdata/book/rootlooponly.yml
  testdata/testloop_count0.golden
  testdata/testloop_count1.golden
  testdata/testloop_count2.golden
  testdata/testloop_count3.golden
Labels: bug, breaking-change
