Repository k1LoW/runn, pull requests merged in 2023-07, with the labels that each got.

#553 Fix a bug that prevented requests with multipart/form-data when the value is numeric
  http.go
  http_test.go
Labels: bug

#547 Enable configurable http runner timeout
  book.go
  integration_test.go
  option.go
  option_test.go
  runner_option.go
  runner_option_test.go
  testdata/book/http_timeout.yml
Labels: enhancement

#556 Keep cookies in store
  builtin/url.go
  http.go
  http_test.go
  integration_test.go
  operator.go
  option.go
  option_test.go
  store.go
  store_test.go
  testdata/book/cookie.yml
Labels: enhancement, minor

#560 Fix values of stepMapKeys that were not being deleted in the loop.
  operator.go
  store.go
Labels: bug

#564 Only for string, expand gRPC messages
  grpc.go
  operator_test.go
  parse.go
  testdata/book/grpc_with_json.json
  testdata/book/grpc_with_json.yml
  testdata/book/http_with_json.json
  testdata/book/http_with_json.yml
Labels: bug

#559 Append use cookie option
  README.md
  book.go
  http.go
  http_test.go
  integration_test.go
  option.go
  parse.go
  parse_test.go
  runner_option.go
  runner_option_test.go
  testdata/book/cookie_in_requests_automatically.yml
Labels: enhancement, minor

#558 Add design doc for runbook ID
  .github/workflows/ci.yml
  Makefile
  docs/designs/id.md
  go.mod
  go.sum
  id_test.go
  include.go
Labels: enhancement, minor, breaking-change

#570 Rename ID to Trail
  capture/runbook.go
  capturer.go
  cmd/rprof.go
  cmdout.go
  debugger.go
  operator.go
  step.go
  trail.go
Labels: breaking-change

#571 Generate IDs using file path of runbooks.
  id.go
  id_test.go
  operator.go
Labels: enhancement, minor, breaking-change

#572 Add methods to specify runbook ID
  book.go
  cmd/run.go
  flags/flags.go
  operator.go
  operator_test.go
  option.go
Labels: enhancement

#573 Add show ids in `runn list` command
  cmd/list.go
  flags/flags.go
  operator.go
Labels: enhancement

#574 Set runnbook ID to result (STDOUT/JSON)
  operator.go
  operator_test.go
  result.go
  result_test.go
  testdata/result_out_0.golden
  testdata/result_out_1.golden
  testdata/result_out_2.golden
  testdata/result_out_json_0.golden
  testdata/result_out_json_1.golden
  testdata/result_out_json_2.golden
Labels: enhancement, breaking-change
