Repository k1LoW/runn, pull requests merged in 2023-05, with the labels that each got.

#497 Fix an issue that the JSON value in the request body becomes a string when it contains newlines.
  eval.go
  go.mod
  go.sum
  runbook.go
  testdata/book/httpbin_include.yml
  testdata/newline.json
  vars_test.go
Labels: bug

#499 Support for JSON type columns
  db.go
  db_test.go
Labels: enhancement, minor, breaking-change

#506 Use google.golang.org/protobuf/reflect/protoreflect instead of github.com/jhump/protoreflect
  README.md
  cdp_test.go
  go.mod
  go.sum
  grpc.go
  grpc_test.go
  include_test.go
  operator.go
  operator_test.go
  option.go
  result.go
Labels: minor, breaking-change

#508 Support yaml:// scheme for vars
  testdata/vars.yaml
  vars.go
  vars_test.go
Labels: enhancement, minor

#511 Add `timeout:` section for gRPC Runner
  go.mod
  go.sum
  grpc.go
  grpc_test.go
  parse.go
  testutil/grpc.go
Labels: enhancement, minor

#516 Add `faker.*` to built-in functions for generating random data
  README.md
  builtin/faker.go
  go.mod
  go.sum
  operator_test.go
  option.go
  option_test.go
  testdata/book/faker.yml
Labels: enhancement, minor

#517 Set gRPC error message to store
  grpc.go
  testdata/book/grpc.yml
  testdata/grpc.yml.debugger.golden
  testdata/grpc.yml.runbook.golden
  testutil/grpc.go
Labels: minor, breaking-change

#519 Change CaptureGRPCResponseStatus signature
  capture/runbook.go
  capturer.go
  cmdout.go
  debugger.go
  grpc.go
  testdata/grpc.yml.debugger.golden
Labels: minor, breaking-change
