Repository k1LoW/runn, pull requests merged in 2023-12, with the labels that each got.

#702 Implicitly enable scope `run:parent` if `--and-run` is enabled
  cmd/new.go
Labels: bug

#706 Fixe a bug that caused other values to change when bind.
  bind.go
  testdata/book/loop.yml
Labels: bug

#711 Add workaround for go-sql-spanner internal connection sharing
  db.go
Labels: bug

#714 Introduce pick() expr built-in function
  README.md
  builtin/pick.go
  builtin/pick_test.go
  option.go
  option_test.go
  testdata/book/builtin_pick.yml
Labels: enhancement

#719 Introduce omit() expr built-in function
  README.md
  builtin/omit.go
  builtin/omit_test.go
  option.go
  option_test.go
  testdata/book/builtin_omit.yml
Labels: enhancement

#721 Update expr (change org)
  CREDITS
  README.md
  bind.go
  bind_test.go
  eval.go
  go.mod
  go.sum
Labels: minor

#724 Fix detectRunbookAreas() failure when the runbook has only 1 step in maps format
  runbook.go
  runbook_test.go
  testdata/book/single_step.yml
  testdata/book/single_step_map.yml
  testdata/pick_step.single_step.yml.0.golden
  testdata/pick_step.single_step_map.yml.0.golden
Labels: bug

#722 Support using YAML's anchors and aliases in runbooks
  http.go
  runbook.go
  runbook_test.go
  testdata/book/yaml_anchor_alias.yml
  testdata/book/yaml_anchor_alias_always_failure.yml
  testdata/pick_step.yaml_anchor_alias.yml.0.golden
  testdata/pick_step.yaml_anchor_alias.yml.7.golden
  testdata/pick_step.yaml_anchor_alias_always_failure.yml.0.golden
  testdata/pick_step.yaml_anchor_alias_always_failure.yml.1.golden
Labels: enhancement, minor
