Repository k1LoW/runn, pull requests merged in 2023-10, with the labels that each got.

#622 Support `exec.shell:` for specifying the shell to use
  README.md
  capture/runbook.go
  capturer.go
  cmdout.go
  debugger.go
  exec.go
  exec_test.go
  parse.go
  testdata/book/exec.yml
  testdata/exec.yml.debugger.golden
  testdata/exec.yml.runbook.golden
  testdata/include_main.yml.runbook.golden
Labels: enhancement, minor, breaking-change

#625 Add `coverage` command for showing coverage for paths/operations of OpenAPI spec and methods of protocol buffers.
  book.go
  cmd/coverage.go
  coverage.go
  coverage_test.go
  grpc.go
  operator.go
  testdata/book/grpc.yml
  testdata/grpc.yml.coverage.json.golden
  testdata/httpbin.yml.coverage.json.golden
Labels: bug, enhancement, minor

#626 Add `--http-openapi3` opiton to set the path to the OpenAPI v3 document for all HTTP runners
  book.go
  cmd/coverage.go
  cmd/loadt.go
  cmd/run.go
  flags/flags.go
  operator.go
  option.go
Labels: enhancement

#627 Consider the path of `servers:` in OpenAPI Spec and endpoint of HTTP runners for coverage path resolution.
  coverage.go
Labels: bug

#629 `coverage` command support JSON output
  cmd/coverage.go
  coverage.go
  operator.go
Labels: enhancement

#630 Show total coverage
  cmd/coverage.go
Labels: enhancement

#635 Fix buildTree (support negative numbers)
  eval.go
  eval_test.go
Labels: bug

#637 Negative numbers are now passed as int type as they are.
  go.mod
  go.sum
  include_test.go
  testdata/book/multiple_include_b.yml
  testdata/book/multiple_include_main.yml
Labels: bug, minor, breaking-change

#639 Update pkgs
  go.mod
  go.sum
Labels: minor

#642 If coverage cannot be collected, report an error.
  cmd/coverage.go
  testdata/book/cookie_in_requests_automatically.yml
Labels: bug

#643 Sort specs of coverage
  operator.go
Labels: bug

#647 Enable to specify OpenAPI3 documents for each HTTP runner.
  book.go
  cmd/coverage.go
  cmd/loadt.go
  cmd/run.go
  coverage.go
  flags/flags.go
  operator.go
  option.go
  path.go
Labels: enhancement, minor, breaking-change

#649 Enable to specify protos for each gRPC runner.
  flags/flags.go
  operator.go
  option.go
Labels: enhancement, breaking-change

#646 Add runbookID() for returning the runbook ID of the root runbook.
  cmd/rprof.go
  operator.go
  operator_test.go
  step.go
  step_test.go
  trail.go
Labels: breaking-change

#651 Pass `*step` at the time of running the runner.
  README.md
  bind.go
  bind_test.go
  cdp.go
  cdp_test.go
  db.go
  db_test.go
  dump.go
  dump_test.go
  exec.go
  exec_test.go
  grpc.go
  grpc_test.go
  http.go
  http_test.go
  include.go
  include_test.go
  operator.go
  ssh.go
  test.go
  test_test.go
Labels: minor, breaking-change

#645 Add header for trace
  .golangci.yml
  book.go
  http.go
  http_test.go
  integration_test.go
  option.go
  parse.go
  parse_test.go
  runner_option.go
  runner_option_test.go
  testdata/book/http_with_use_trace.yml
  trace.go
Labels: enhancement, minor

#654 Add comment to query statement for trace
  book.go
  db.go
  db_test.go
  include_test.go
  operator_test.go
  option.go
  option_test.go
  parse.go
  runner_option.go
  runner_option_test.go
  testdata/book/db.yml
  testdata/db.yml.runbook.golden
Labels: enhancement, minor, breaking-change

#655 Fix handling of gRPC headers
  capture/runbook.go
  grpc.go
  parse.go
  testdata/book/grpc.yml
  testdata/grpc.yml.debugger.golden
  testdata/grpc.yml.runbook.golden
Labels: bug

#656 Support header for tracing gRPC requests
  book.go
  db_test.go
  grpc.go
  grpc_test.go
  parse.go
  runner_option.go
Labels: enhancement, minor

#657 Fix handling of http headers
  http.go
  http_test.go
  parse.go
  parse_test.go
  testdata/book/http.yml
  testdata/http.yml.debugger.golden
  testdata/http.yml.runbook.golden
  testdata/pick_step.http.yml.8.golden
Labels: bug

#658 Support `trace:` for tracing
  book.go
  db.go
  grpc.go
  http.go
  include.go
  operator.go
  operator_test.go
  option.go
  runbook.go
  runner_option_test.go
Labels: enhancement, minor

#662 Error if the file does not exist.
  operator_test.go
  path.go
  path_test.go
  testdata/book/include_vars_included.yml
  testdata/book/include_vars_main.yml
Labels: minor, breaking-change

#664 Fix single value expand
  .github/workflows/ci.yml
  eval.go
  eval_test.go
  go.mod
  go.sum
  testdata/book/include_vars_included.yml
  testdata/book/include_vars_main.yml
Labels: enhancement, minor, breaking-change

#663 Add the concept of scope.
  README.md
  book.go
  book_test.go
  capture/runbook_test.go
  cmd/root.go
  flags/flags.go
  integration_test.go
  operator.go
  option.go
  path.go
  scope.go
  testdata/book/sshd_local_forward.yml
  testutil/port.go
Labels: enhancement, minor, breaking-change

#667 Add `run:exec` scope. and deny by default.
  README.md
  capture/runbook_test.go
  debugger_test.go
  exec.go
  exec_test.go
  integration_test.go
  operator_test.go
  profile_test.go
  scope.go
  trail.go
Labels: enhancement, breaking-change
