Repository k1LoW/runn, pull requests merged in 2024-06, with the labels that each got.

#945 Support `--env-file` option for loading environment variables from a file.
  cmd/coverage.go
  cmd/list.go
  cmd/loadt.go
  cmd/run.go
  env.go
  env_test.go
  flags/flags.go
  go.mod
  go.sum
Labels: enhancement, minor

#936 Add jq path syntax support for excluding comparison targets in diff()/compare() functions.
  README.md
  builtin/compare.go
  builtin/compare_test.go
  builtin/diff.go
  builtin/diff_test.go
  go.mod
  go.sum
Labels: minor, breaking-change

#951 Add `--force-color` option for forcing colorized output
  cmd/run.go
  flags/flags.go
Labels: enhancement, minor

#958 Improve implementation of the built-in function `select`.
  README.md
  option.go
Labels: enhancement

#963 Support buf v2 configration files.
  go.mod
  go.sum
Labels: enhancement

#964 Update bufresolv
  go.mod
  go.sum
Labels: bug

#966 Add "Runner runner" that allows runners to be defined in the middle of steps.
  README.md
  book.go
  operator.go
  operator_test.go
  runner_runner.go
  runner_runner_test.go
  step.go
  testdata/book/runner_runner.yml
Labels: enhancement, minor

#968 Fix a bug where runners defined in runner runners could not be used in combination with test runner or dump runner.
  step.go
  testdata/book/runner_runner.yml
Labels: bug

#970 Update bufresolv
  go.mod
  go.sum
Labels: bug

#978 Fix Runner runner root path
  runner_runner.go
Labels: bug

#979 Fix loadt output
  cmd/loadt.go
  cmd/spinner.go
  go.mod
  go.sum
Labels: breaking-change
