Repository k1LoW/runn, pull requests merged in 2024-08, with the labels that each got.

#1002 Support for the combined use of Include Runner and `needs:`
  cmdout.go
  cmdout_test.go
  include.go
  operator.go
  operator_test.go
  result.go
  result_test.go
  step.go
  testdata/book/needs_3.yml
  testdata/book/needs_4.yml
  testdata/book/needs_5.yml
  testdata/result_out_json_3.golden
Labels: minor, breaking-change

#1006 Support for the combined use of Include Runner and `needs:`
  cmdout.go
  cmdout_test.go
  include.go
  operator.go
  operator_test.go
  result.go
  result_test.go
  step.go
  testdata/book/needs_3.yml
  testdata/book/needs_4.yml
  testdata/book/needs_5.yml
  testdata/result_out_json_3.golden
Labels: enhancement, breaking-change

#1008 Propagate runn.kv / add tests
  include.go
  operator.go
  operator_test.go
  testdata/book/needs_3.yml
  testdata/book/needs_4.yml
Labels: bug

#1010 Fix the output of `runn new` for a gRPC method which needs a empty message
  runbook.go
Labels: bug

#1017 Results for `needs:` are not overwritten.
  go.mod
  go.sum
  operator.go
Labels: minor, breaking-change

#1018 If there are runbook run failures in `runn run`, list the failure results at the end (always).
  cmd/run.go
  result.go
  result_test.go
  testdata/result_out_0.golden
  testdata/result_out_1.golden
  testdata/result_out_2.golden
Labels: breaking-change

#948 Use gprc.NewClient instead of grpc.DialContext.
  grpc.go
Labels: breaking-change
