Repository k1LoW/runn, pull requests merged in 2024-01, with the labels that each got.

#734 Update benchmarks
  Makefile
  benchmark_test.go
  testutil/runbook.go
Labels: breaking-change

#738 Revert inexplicable Unmarshal
  operator.go
  result_test.go
Labels: bug

#742 Specify the header name for the trace header
  book.go
  book_test.go
  grpc.go
  grpc_test.go
  http.go
  http_test.go
  integration_test.go
  operator_test.go
  option.go
  option_test.go
  runner_option.go
  runner_option_test.go
  testdata/book/http_with_use_trace_header_name.yml
  trace.go
Labels: enhancement, minor

#739 RE Disable profile by default
  book.go
  cmd/loadt.go
  cmd/run.go
  flags/flags.go
  include.go
  operator.go
  option.go
  profile_test.go
  result_test.go
Labels: minor, breaking-change

#752 uint64 that came across from the include runner can also be used for loop count.
  eval.go
  eval_test.go
Labels: bug

#753 Trim unnecessary CR and LF in queries
  db.go
  db_test.go
Labels: bug

#754 Support for `hostRules:` (control of hostname/IP mapping) in HTTP runner, gRPC runner and CDP runner
  book.go
  go.mod
  grpc.go
  hosts.go
  hosts_test.go
  operator.go
  operator_test.go
  runbook.go
  testdata/book/cdp_with_host_rules.yml
  testdata/book/cdp_with_host_rules_wildcard.yml
  testdata/book/grpc_with_host_rules.yml
  testdata/book/grpc_with_host_rules_wildcard.yml
  testdata/book/http_with_host_rules.yml
  testdata/book/http_with_host_rules_wildcard.yml
Labels: enhancement, minor

#756 Add `--host-rules` option to loadt and run commands.
  cmd/loadt.go
  cmd/run.go
  flags/flags.go
  option.go
  option_test.go
Labels: enhancement

#757 Use `--host-resolver-rules` instead of `--host-rules` in CDP Runner
  hosts.go
Labels: bug

#764 Delay connection of DB runner and SSH runner to target as long as possible.
  book.go
  cmd/runn/main.go
  db.go
  hosts.go
  hosts_test.go
  integration_test.go
  ssh.go
  ssh_test.go
  testdata/book/sshd_with_host_rules.yml
  testdata/book/sshd_with_host_rules_wildcard.yml
  testdata/sshd/ssh_config
  testutil/ssh.go
Labels: enhancement, minor, breaking-change

#763 Support host rules in SSH Runner
  README.md
  book.go
  cmd/runn/main.go
  db.go
  go.mod
  go.sum
  hosts.go
  hosts_test.go
  integration_test.go
  operator.go
  operator_test.go
  ssh.go
  ssh_test.go
  testdata/book/sshd_with_host_rules.yml
  testdata/book/sshd_with_host_rules_wildcard.yml
  testdata/sshd/ssh_config
  testutil/port.go
  testutil/ssh.go
Labels: enhancement, minor, breaking-change

#766 Output results step by step when the `--verbose` option is enabled (Update `runn.Capturer` interface)
  capture/runbook.go
  capturer.go
  cmdout.go
  cmdout_test.go
  debugger.go
  operator.go
  testdata/runn_cmdout_1.golden
  testdata/runn_cmdout_by_step0.golden
  testdata/runn_cmdout_by_step1.golden
Labels: enhancement

#768 Reflect skipValidateRequest when http-openapi3 option is enabled
  operator.go
  operator_test.go
  testdata/book/http_skip_validate_request.yml
Labels: bug

#769 Keep loaded OpenAPI documents
  http_validator.go
Labels: enhancement, minor

#772 Support multiple concurrency keys
  README.md
  book.go
  go.mod
  go.sum
  operator.go
  runbook.go
Labels: enhancement, minor

#778 Fix verbose index
  cmdout.go
  cmdout_test.go
  testdata/runn_cmdout_by_step2.golden
Labels: bug
