Repository k1LoW/runn, pull requests merged in 2024-02, with the labels that each got.

#781 fix: Fix potential panic
  operator.go
Labels: bug

#782 Set default output for Dump runner
  operator.go
  operator_test.go
  testdata/book/dump.yml
Labels: enhancement

#786 Fix concurrency
  book.go
  runbook.go
  testdata/book/concurrency.yml
Labels: bug

#787 Support `gist://` scheme
  go.mod
  go.sum
  path.go
  path_test.go
Labels: enhancement, minor

#789 Set up donegroup and timeout for waiting cleanup processes after context canceled
  book.go
  cmd/loadt.go
  cmd/run.go
  flags/flags.go
  go.mod
  go.sum
  operator.go
  option.go
Labels: minor, breaking-change

#790 Remove deprecated code
  builtin/json.go
  option.go
  option_test.go
Labels: breaking-change

#793 Fix error handling
  .github/workflows/ci.yml
  cmd/run.go
Labels: bug

#805 Support Custom runner (using Include runner)
  bind_test.go
  book.go
  builtin/keys.go
  cdp_test.go
  db_test.go
  dump_test.go
  exec_test.go
  grpc_test.go
  http_test.go
  include.go
  include_test.go
  operator.go
  operator_test.go
  option.go
  option_test.go
  parse.go
  runner_option.go
  step.go
  store.go
  store_test.go
  test_test.go
  testdata/book/custom_runner_default_header.yml
  testdata/book/custom_runner_gqlreq.yml
  testdata/book/custom_runner_http.yml
  testdata/book/custom_runners.yml
  testdata/book/http.yml
  testdata/book/http_multipart.yml
  testdata/book/http_not_follow_redirect.yml
  testdata/book/http_skip_validate_request.yml
  testdata/book/http_with_json.yml
  testdata/book/store_keys.yml
  testdata/http.yml.runbook.golden
  testdata/http_multipart.yml.runbook.golden
  testutil/http.go
Labels: enhancement, minor, breaking-change

#811 Add builtin functions for ID generation to `faker.*`
  builtin/faker.go
  go.mod
  go.sum
Labels: enhancement

#814 Add `runn.kv` for injecting value to running scenarios from external threads.
  bind_test.go
  include.go
  kv.go
  kv_test.go
  operator.go
  store.go
  store_test.go
  testdata/book/kv.yml
Labels: enhancement

#815 Fix verbose output
  cmdout.go
  testdata/runn_cmdout_by_step1.golden
Labels: bug

#817 Add `--attach` option for debugging or step execution
  book.go
  cmd/run.go
  dbg.go
  flags/flags.go
  go.mod
  go.sum
  include.go
  operator.go
  operator_test.go
  option.go
Labels: enhancement
