Repository k1LoW/runn, pull requests merged in 2024-11, with the labels that each got.

#1063 Live output support for exec runner
  README.md
  exec.go
  parse.go
  testdata/book/exec.yml
  testdata/exec.yml.debugger.golden
  testdata/exec.yml.runbook.golden
Labels: enhancement, minor

#1068 Fix remote fetch (Support for other directories of remote files)
  path.go
Labels: bug

#1070 Update goccy/go-yaml to v1.14.3
  go.mod
  go.sum
  parse_test.go
  testdata/pick_step.yaml_anchor_alias.yml.0.golden
  testdata/pick_step.yaml_anchor_alias_always_failure.yml.0.golden
Labels: minor, breaking-change

#1076 Implement `secrets:` section
  README.md
  book.go
  debugger_test.go
  dump.go
  dump_test.go
  exec.go
  exec_test.go
  go.mod
  go.sum
  operator.go
  operator_test.go
  option.go
  store.go
  testdata/book/with_secrets.yml
  testdata/with_secrets.yml.debugger.golden
Labels: enhancement, minor

#1077 Fix hasRemotePrefix ( add prefixGist )
  path.go
Labels: bug

#1080 Allow absolute paths and enhance scopes detection
  book.go
  cache.go
  cdp.go
  coverage_test.go
  debugger_test.go
  hosts_test.go
  http.go
  include.go
  operator.go
  operator_test.go
  option.go
  path.go
  path_test.go
  runbook.go
Labels: bug, minor, breaking-change

#1081 Support `file://` scheme.
  include.go
  path.go
  path_test.go
  testdata/book/http.yml
  testdata/book/include_main.yml
  testdata/http.yml.runbook.golden
Labels: enhancement

#1082 Make it possible to explicitly specify files in multipart/form-data requests in the HTTP runner
  http.go
  http_test.go
Labels: breaking-change

#1086 Revert goccy/go-yaml and k1LoW/expand
  go.mod
  go.sum
  testdata/book/httpbin.yml
  testdata/httpbin.yml.coverage.json.golden
  testdata/pick_step.single_step_map.yml.0.golden
  testdata/pick_step.yaml_anchor_alias.yml.0.golden
  testdata/pick_step.yaml_anchor_alias_always_failure.yml.0.golden
Labels: bug
