Repository k1LoW/runn, pull requests merged in 2024-05, with the labels that each got.

#908 Support Buf ecosystem
  README.md
  book.go
  cmd/coverage.go
  cmd/loadt.go
  cmd/run.go
  flags/flags.go
  go.mod
  go.sum
  grpc.go
  grpc_test.go
  operator.go
  option.go
  runner_option.go
  testdata/book/grpc.yml
  testdata/book/grpc_with_host_rules.yml
  testdata/book/grpc_with_host_rules_wildcard.yml
  testdata/grpc.yml.runbook.golden
Labels: enhancement, minor, breaking-change

#909 Introduce protoresolv so that protos under it are automatically loaded simply by specifying importPaths.
  README.md
  go.mod
  go.sum
  grpc.go
Labels: minor, breaking-change

#921 Fix a missing line bug when including a multi-line string.
  eval.go
  include_test.go
  testdata/book/include_vars_included.yml
  testdata/book/include_vars_main.yml
Labels: bug

#923 Print deprecation warnings
  operator.go
  runner_option.go
  warning.go
Labels: breaking-change

#917 Replace the buildTree() method by injected expr tracing approach
  eval.go
  eval_test.go
  exprtrace/eval.go
  exprtrace/tracer.go
  exprtrace/tracer_test.go
  exprtrace/tree_printer.go
  loadt.go
  operator.go
  test.go
  testdata/book/http_skip_validate_request.yml
  testdata/book/httpbin.yml
  testdata/book/loop.yml
Labels: enhancement, minor, breaking-change

#925 Print diff info for the compare() built-in function (issue #803)
  eval.go
  eval_test.go
  exprtrace/eval.go
  exprtrace/tree_printer.go
Labels: minor, breaking-change

#933 Remove `steps[*].run` `steps.<key>.run` from store
  bind_test.go
  db_test.go
  exec_test.go
  operator.go
  operator_test.go
  store.go
Labels: breaking-change

#935 Support negative label condition
  operator.go
  operator_test.go
Labels: enhancement, minor

#943 Add `exec.background:` for executing commands in the background.
  README.md
  capture/runbook.go
  capture/runbook_test.go
  capturer.go
  cmdout.go
  debugger.go
  exec.go
  exec_test.go
  go.mod
  go.sum
  parse.go
  testdata/book/exec.yml
  testdata/exec.yml.debugger.golden
  testdata/exec.yml.runbook.golden
Labels: enhancement, minor, breaking-change

#944 Fix a significant deviation in verbose output.
  cmdout.go
  cmdout_test.go
  operator.go
  operator_test.go
  result.go
  testdata/book/include_a.yml
  testdata/book/include_main.yml
  testdata/runn_cmdout_by_step1.golden
Labels: bug

#946 Support `--format none` to disable output.
  cmd/run.go
Labels: enhancement
