Repository k1LoW/runn, pull requests merged in 2025-01, with the labels that each got.

#1143 fix(loadt): Fix a bug that overwrote the original error
  cmd/loadt.go
Labels: bug

#1145 If loop.count <= 0, skip step.
  operator.go
  testdata/book/loop.yml
Labels: minor, breaking-change

#1150 Fix loadt stucked
  Makefile
  cmd/loadt.go
Labels: bug

#1157 fix: Temporarily revert version of goccy/go-json to support data race
  .github/dependabot.yml
  go.mod
  go.sum
  hosts_test.go
Labels: dependencies

#1162 chore: Bump up go directive version
  go.mod
Labels: go
